// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: psu.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "psu.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Hackers_Project {

namespace {

const ::google::protobuf::Descriptor* psu_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  psu_data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_psu_2eproto() {
  protobuf_AddDesc_psu_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "psu.proto");
  GOOGLE_CHECK(file != NULL);
  psu_data_descriptor_ = file->message_type(0);
  static const int psu_data_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(psu_data, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(psu_data, energy_generated_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(psu_data, technology_required_),
  };
  psu_data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      psu_data_descriptor_,
      psu_data::default_instance_,
      psu_data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(psu_data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(psu_data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(psu_data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_psu_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    psu_data_descriptor_, &psu_data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_psu_2eproto() {
  delete psu_data::default_instance_;
  delete psu_data_reflection_;
}

void protobuf_AddDesc_psu_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tpsu.proto\022\017Hackers_Project\"O\n\010psu_data"
    "\022\014\n\004name\030\001 \002(\t\022\030\n\020energy_generated\030\002 \002(\r"
    "\022\033\n\023technology_required\030\003 \002(\t", 109);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "psu.proto", &protobuf_RegisterTypes);
  psu_data::default_instance_ = new psu_data();
  psu_data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_psu_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_psu_2eproto {
  StaticDescriptorInitializer_psu_2eproto() {
    protobuf_AddDesc_psu_2eproto();
  }
} static_descriptor_initializer_psu_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int psu_data::kNameFieldNumber;
const int psu_data::kEnergyGeneratedFieldNumber;
const int psu_data::kTechnologyRequiredFieldNumber;
#endif  // !_MSC_VER

psu_data::psu_data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void psu_data::InitAsDefaultInstance() {
}

psu_data::psu_data(const psu_data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void psu_data::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  energy_generated_ = 0u;
  technology_required_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

psu_data::~psu_data() {
  SharedDtor();
}

void psu_data::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (technology_required_ != &::google::protobuf::internal::kEmptyString) {
    delete technology_required_;
  }
  if (this != default_instance_) {
  }
}

void psu_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* psu_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return psu_data_descriptor_;
}

const psu_data& psu_data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_psu_2eproto();
  return *default_instance_;
}

psu_data* psu_data::default_instance_ = NULL;

psu_data* psu_data::New() const {
  return new psu_data;
}

void psu_data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    energy_generated_ = 0u;
    if (has_technology_required()) {
      if (technology_required_ != &::google::protobuf::internal::kEmptyString) {
        technology_required_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool psu_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_energy_generated;
        break;
      }

      // required uint32 energy_generated = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_energy_generated:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &energy_generated_)));
          set_has_energy_generated();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_technology_required;
        break;
      }

      // required string technology_required = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_technology_required:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_technology_required()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->technology_required().data(), this->technology_required().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void psu_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // required uint32 energy_generated = 2;
  if (has_energy_generated()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->energy_generated(), output);
  }

  // required string technology_required = 3;
  if (has_technology_required()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->technology_required().data(), this->technology_required().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->technology_required(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* psu_data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required uint32 energy_generated = 2;
  if (has_energy_generated()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->energy_generated(), target);
  }

  // required string technology_required = 3;
  if (has_technology_required()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->technology_required().data(), this->technology_required().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->technology_required(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int psu_data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required uint32 energy_generated = 2;
    if (has_energy_generated()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->energy_generated());
    }

    // required string technology_required = 3;
    if (has_technology_required()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->technology_required());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void psu_data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const psu_data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const psu_data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void psu_data::MergeFrom(const psu_data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_energy_generated()) {
      set_energy_generated(from.energy_generated());
    }
    if (from.has_technology_required()) {
      set_technology_required(from.technology_required());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void psu_data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void psu_data::CopyFrom(const psu_data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool psu_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void psu_data::Swap(psu_data* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(energy_generated_, other->energy_generated_);
    std::swap(technology_required_, other->technology_required_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata psu_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = psu_data_descriptor_;
  metadata.reflection = psu_data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Hackers_Project

// @@protoc_insertion_point(global_scope)
