// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cpu.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cpu.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Hackers_Project {

namespace {

const ::google::protobuf::Descriptor* cpu_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  cpu_data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_cpu_2eproto() {
  protobuf_AddDesc_cpu_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "cpu.proto");
  GOOGLE_CHECK(file != NULL);
  cpu_data_descriptor_ = file->message_type(0);
  static const int cpu_data_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(cpu_data, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(cpu_data, energy_consumption_),
  };
  cpu_data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      cpu_data_descriptor_,
      cpu_data::default_instance_,
      cpu_data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(cpu_data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(cpu_data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(cpu_data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_cpu_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    cpu_data_descriptor_, &cpu_data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_cpu_2eproto() {
  delete cpu_data::default_instance_;
  delete cpu_data_reflection_;
}

void protobuf_AddDesc_cpu_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tcpu.proto\022\017Hackers_Project\"4\n\010cpu_data"
    "\022\014\n\004name\030\001 \002(\t\022\032\n\022energy_consumption\030\002 \002"
    "(\r", 82);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cpu.proto", &protobuf_RegisterTypes);
  cpu_data::default_instance_ = new cpu_data();
  cpu_data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_cpu_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_cpu_2eproto {
  StaticDescriptorInitializer_cpu_2eproto() {
    protobuf_AddDesc_cpu_2eproto();
  }
} static_descriptor_initializer_cpu_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int cpu_data::kNameFieldNumber;
const int cpu_data::kEnergyConsumptionFieldNumber;
#endif  // !_MSC_VER

cpu_data::cpu_data()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void cpu_data::InitAsDefaultInstance() {
}

cpu_data::cpu_data(const cpu_data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void cpu_data::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  energy_consumption_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

cpu_data::~cpu_data() {
  SharedDtor();
}

void cpu_data::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void cpu_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* cpu_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return cpu_data_descriptor_;
}

const cpu_data& cpu_data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_cpu_2eproto();
  return *default_instance_;
}

cpu_data* cpu_data::default_instance_ = NULL;

cpu_data* cpu_data::New() const {
  return new cpu_data;
}

void cpu_data::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    energy_consumption_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool cpu_data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_energy_consumption;
        break;
      }

      // required uint32 energy_consumption = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_energy_consumption:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &energy_consumption_)));
          set_has_energy_consumption();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void cpu_data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }

  // required uint32 energy_consumption = 2;
  if (has_energy_consumption()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->energy_consumption(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* cpu_data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // required uint32 energy_consumption = 2;
  if (has_energy_consumption()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->energy_consumption(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int cpu_data::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required uint32 energy_consumption = 2;
    if (has_energy_consumption()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->energy_consumption());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void cpu_data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const cpu_data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const cpu_data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void cpu_data::MergeFrom(const cpu_data& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_energy_consumption()) {
      set_energy_consumption(from.energy_consumption());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void cpu_data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void cpu_data::CopyFrom(const cpu_data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool cpu_data::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void cpu_data::Swap(cpu_data* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(energy_consumption_, other->energy_consumption_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata cpu_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = cpu_data_descriptor_;
  metadata.reflection = cpu_data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Hackers_Project

// @@protoc_insertion_point(global_scope)
