// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cybermatrix.proto

#ifndef PROTOBUF_cybermatrix_2eproto__INCLUDED
#define PROTOBUF_cybermatrix_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Hackers_Project {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cybermatrix_2eproto();
void protobuf_AssignDesc_cybermatrix_2eproto();
void protobuf_ShutdownFile_cybermatrix_2eproto();

class entity_data;
class cybermatrix_data;

// ===================================================================

class entity_data : public ::google::protobuf::Message {
 public:
  entity_data();
  virtual ~entity_data();

  entity_data(const entity_data& from);

  inline entity_data& operator=(const entity_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const entity_data& default_instance();

  void Swap(entity_data* other);

  // implements Message ----------------------------------------------

  entity_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const entity_data& from);
  void MergeFrom(const entity_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Hackers_Project.entity_data)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_cybermatrix_2eproto();
  friend void protobuf_AssignDesc_cybermatrix_2eproto();
  friend void protobuf_ShutdownFile_cybermatrix_2eproto();

  void InitAsDefaultInstance();
  static entity_data* default_instance_;
};
// -------------------------------------------------------------------

class cybermatrix_data : public ::google::protobuf::Message {
 public:
  cybermatrix_data();
  virtual ~cybermatrix_data();

  cybermatrix_data(const cybermatrix_data& from);

  inline cybermatrix_data& operator=(const cybermatrix_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cybermatrix_data& default_instance();

  void Swap(cybermatrix_data* other);

  // implements Message ----------------------------------------------

  cybermatrix_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cybermatrix_data& from);
  void MergeFrom(const cybermatrix_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required uint32 energy_consumption = 2;
  inline bool has_energy_consumption() const;
  inline void clear_energy_consumption();
  static const int kEnergyConsumptionFieldNumber = 2;
  inline ::google::protobuf::uint32 energy_consumption() const;
  inline void set_energy_consumption(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Hackers_Project.cybermatrix_data)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_energy_consumption();
  inline void clear_has_energy_consumption();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::google::protobuf::uint32 energy_consumption_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_cybermatrix_2eproto();
  friend void protobuf_AssignDesc_cybermatrix_2eproto();
  friend void protobuf_ShutdownFile_cybermatrix_2eproto();

  void InitAsDefaultInstance();
  static cybermatrix_data* default_instance_;
};
// ===================================================================


// ===================================================================

// entity_data

// -------------------------------------------------------------------

// cybermatrix_data

// required string name = 1;
inline bool cybermatrix_data::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cybermatrix_data::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cybermatrix_data::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cybermatrix_data::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& cybermatrix_data::name() const {
  return *name_;
}
inline void cybermatrix_data::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void cybermatrix_data::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void cybermatrix_data::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* cybermatrix_data::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* cybermatrix_data::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void cybermatrix_data::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required uint32 energy_consumption = 2;
inline bool cybermatrix_data::has_energy_consumption() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cybermatrix_data::set_has_energy_consumption() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cybermatrix_data::clear_has_energy_consumption() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cybermatrix_data::clear_energy_consumption() {
  energy_consumption_ = 0u;
  clear_has_energy_consumption();
}
inline ::google::protobuf::uint32 cybermatrix_data::energy_consumption() const {
  return energy_consumption_;
}
inline void cybermatrix_data::set_energy_consumption(::google::protobuf::uint32 value) {
  set_has_energy_consumption();
  energy_consumption_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Hackers_Project

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cybermatrix_2eproto__INCLUDED
