// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyberentities.proto

#ifndef PROTOBUF_cyberentities_2eproto__INCLUDED
#define PROTOBUF_cyberentities_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Hackers_Project {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_cyberentities_2eproto();
void protobuf_AssignDesc_cyberentities_2eproto();
void protobuf_ShutdownFile_cyberentities_2eproto();

class cyberentities_data;

enum cyberentities_data_entites_type {
  cyberentities_data_entites_type_Player = 1,
  cyberentities_data_entites_type_AI = 2,
  cyberentities_data_entites_type_Firewall = 3,
  cyberentities_data_entites_type_Transport = 4,
  cyberentities_data_entites_type_Detector = 5
};
bool cyberentities_data_entites_type_IsValid(int value);
const cyberentities_data_entites_type cyberentities_data_entites_type_entites_type_MIN = cyberentities_data_entites_type_Player;
const cyberentities_data_entites_type cyberentities_data_entites_type_entites_type_MAX = cyberentities_data_entites_type_Detector;
const int cyberentities_data_entites_type_entites_type_ARRAYSIZE = cyberentities_data_entites_type_entites_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* cyberentities_data_entites_type_descriptor();
inline const ::std::string& cyberentities_data_entites_type_Name(cyberentities_data_entites_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    cyberentities_data_entites_type_descriptor(), value);
}
inline bool cyberentities_data_entites_type_Parse(
    const ::std::string& name, cyberentities_data_entites_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<cyberentities_data_entites_type>(
    cyberentities_data_entites_type_descriptor(), name, value);
}
// ===================================================================

class cyberentities_data : public ::google::protobuf::Message {
 public:
  cyberentities_data();
  virtual ~cyberentities_data();

  cyberentities_data(const cyberentities_data& from);

  inline cyberentities_data& operator=(const cyberentities_data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cyberentities_data& default_instance();

  void Swap(cyberentities_data* other);

  // implements Message ----------------------------------------------

  cyberentities_data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cyberentities_data& from);
  void MergeFrom(const cyberentities_data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef cyberentities_data_entites_type entites_type;
  static const entites_type Player = cyberentities_data_entites_type_Player;
  static const entites_type AI = cyberentities_data_entites_type_AI;
  static const entites_type Firewall = cyberentities_data_entites_type_Firewall;
  static const entites_type Transport = cyberentities_data_entites_type_Transport;
  static const entites_type Detector = cyberentities_data_entites_type_Detector;
  static inline bool entites_type_IsValid(int value) {
    return cyberentities_data_entites_type_IsValid(value);
  }
  static const entites_type entites_type_MIN =
    cyberentities_data_entites_type_entites_type_MIN;
  static const entites_type entites_type_MAX =
    cyberentities_data_entites_type_entites_type_MAX;
  static const int entites_type_ARRAYSIZE =
    cyberentities_data_entites_type_entites_type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  entites_type_descriptor() {
    return cyberentities_data_entites_type_descriptor();
  }
  static inline const ::std::string& entites_type_Name(entites_type value) {
    return cyberentities_data_entites_type_Name(value);
  }
  static inline bool entites_type_Parse(const ::std::string& name,
      entites_type* value) {
    return cyberentities_data_entites_type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .Hackers_Project.cyberentities_data.entites_type type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::Hackers_Project::cyberentities_data_entites_type type() const;
  inline void set_type(::Hackers_Project::cyberentities_data_entites_type value);

  // @@protoc_insertion_point(class_scope:Hackers_Project.cyberentities_data)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_cyberentities_2eproto();
  friend void protobuf_AssignDesc_cyberentities_2eproto();
  friend void protobuf_ShutdownFile_cyberentities_2eproto();

  void InitAsDefaultInstance();
  static cyberentities_data* default_instance_;
};
// ===================================================================


// ===================================================================

// cyberentities_data

// required string name = 1;
inline bool cyberentities_data::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cyberentities_data::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cyberentities_data::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cyberentities_data::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& cyberentities_data::name() const {
  return *name_;
}
inline void cyberentities_data::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void cyberentities_data::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void cyberentities_data::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* cyberentities_data::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* cyberentities_data::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void cyberentities_data::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .Hackers_Project.cyberentities_data.entites_type type = 2;
inline bool cyberentities_data::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cyberentities_data::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cyberentities_data::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cyberentities_data::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::Hackers_Project::cyberentities_data_entites_type cyberentities_data::type() const {
  return static_cast< ::Hackers_Project::cyberentities_data_entites_type >(type_);
}
inline void cyberentities_data::set_type(::Hackers_Project::cyberentities_data_entites_type value) {
  assert(::Hackers_Project::cyberentities_data_entites_type_IsValid(value));
  set_has_type();
  type_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Hackers_Project

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Hackers_Project::cyberentities_data_entites_type>() {
  return ::Hackers_Project::cyberentities_data_entites_type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cyberentities_2eproto__INCLUDED
